name: Update Google Scholar Citations and Publications HTML

on:
  # push:
  #   branches: ["html-update"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install python3-setuptools
      - name: Run
        run: |
          cd ./scripts
          pip3 install -r requirements.txt
          python3 download_scholar_data.py
          python3 generate_publications.py
          cd ../
          git config --local user.name "${GITHUB_ACTOR}"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add .
          git commit -m "Update citations."
          git push "${remote_repo}" HEAD:html-update
